---
title: "Multivocal - data wrangling"
author: "Ajna Kertesz"
date: "6/23/2022"
output: html_document
---


```{r setup}
knitr::opts_chunk$set(fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```



```{r load data and wrangle}
library(tidyverse)
library(readr)
library(dplyr)
library(likert)
library(psych)
library(knitr)
library(plyr)
library(sjPlot)
library(mudata2)
library(utils)
library(car)
library(lme4)

MV_WEIRD <- read_csv("MV_WEIRD_Complete.csv")
MV_code <- read.csv("MV_coded_open_end.csv")

MV_WEIRD <- merge(MV_WEIRD, MV_code,by=c("PID"))


 #select variables
MV_final = MV_WEIRD %>% dplyr::select(Smart, Behave, Grades, Age, Gender, Country, Video_Gender, parent, Education, PID, SES, Edu_asp, income_annual, occupation, Smart_reason, Behave_reason, Grades_reason, Teach_expect_1,Teach_expect_2, Teach_expect_3,Teach_expect_4, Teach_expect_5 ,Teach_expect_6, school_values_1,school_values_2, school_values_3, school_values_4,school_values_5, school_values_6) %>%  
  mutate(Age = as.numeric(Age),
        parent= ifelse(MV_WEIRD$parent=="Yes",1,0))


#recode countries to meaningful characters
MV_final$Country<- recode_factor(MV_final$Country, `1`="US", `2`="Canada", `3`="UK", `4`="Australia", `5`="NZ")

#recode open end responses to meaningful characters
MV_final$Smart_reason<- recode_factor(MV_final$Smart_reason, `1`="Behavioral", `2`="Normative", `3`="Cognitive", `4`="Personality", `5`="Irrelevant", `6`="Null")
MV_final$Behave_reason<- recode_factor(MV_final$Behave_reason, `1`="Behavioral", `2`="Normative", `3`="Cognitive", `4`="Personality", `5`="Irrelevant", `6`="Null")
MV_final$Grades_reason<- recode_factor(MV_final$Grades_reason, `1`="Behavioral", `2`="Normative", `3`="Cognitive", `4`="Personality", `5`="Irrelevant", `6`="Null")


#recode education to less groups
MV_final$Education<- ifelse(grepl("Associate's defree or Certificate/Diploma", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Bachelor's degree or Honors degree", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Associate's degree or Certificate/Diploma", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Some high/secondary school",
MV_final$Education, fixed=TRUE), "Some high school or high school", MV_final$Education)

MV_final$Education<- ifelse(grepl("High/Secondary school",
MV_final$Education, fixed=TRUE), "Some high school or high school", MV_final$Education)

MV_final$Education<- ifelse(grepl("Master's degree",
MV_final$Education, fixed=TRUE), "Post-graduate Degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("PhD or other higher postgraduate degrees",
MV_final$Education, fixed=TRUE), "Post-graduate Degree", MV_final$Education)

MV_final$Education<- ifelse(grepl ("Some high school or high school" , MV_final$Education, fixed=TRUE),"1", MV_final$Education)
MV_final$Education<- ifelse(grepl ("Some college/university" , MV_final$Education, fixed=TRUE),"2", MV_final$Education)

MV_final$Education<- ifelse(grepl ( "Bachelor’s degree or Associate’s degree", MV_final$Education, fixed=TRUE),"3", MV_final$Education)
MV_final$Education<- ifelse(grepl ("Post-graduate Degree" , MV_final$Education, fixed=TRUE),"4", MV_final$Education)

#make education numeric, so we can use it in the analysis
MV_final$Education<- as.numeric(MV_final$Education)


#recode edu asp to numerical values
MV_final$Edu_asp<- ifelse(grepl ("Some high/secondary school" , MV_final$Edu_asp, fixed=TRUE),"1", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("High/Secondary school" , MV_final$Edu_asp, fixed=TRUE),"2", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Some college/university" , MV_final$Edu_asp, fixed=TRUE),"3", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Associate's degree or Certificate/Diploma" , MV_final$Edu_asp, fixed=TRUE),"4",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Bachelor's degree or Honors degree" , MV_final$Edu_asp, fixed=TRUE),"5",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Master's degree" , MV_final$Edu_asp, fixed=TRUE),"6",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("PhD or other higher postgraduate degrees" , MV_final$Edu_asp, fixed=TRUE),"6",MV_final$Edu_asp)


#recode income
#bucket 1
MV_final$income_annual<- ifelse(grepl ("Less than $22,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than $7,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than $21,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than $14,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than - £21,000" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)

unique(MV_final$income_annual)

#bucket 2
MV_final$income_annual<- ifelse(grepl ("$23,000 - $42,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$23,000  - $42,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$8,000 - $16,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$22,000  - $44,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$22,000 - $44,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$15,000  - $29,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$15,000 - $29,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£21,001 - £27,700" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)


#bucket 3
MV_final$income_annual<- ifelse(grepl ("$43,000  - $74,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$43,000 - $74,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$17,000 - $34,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$45,000 - $78,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$45,000  - $78,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$30,000  - $49,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$30,000 - $49,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£27,701 - £43,700" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)



#bucket 4
MV_final$income_annual<- ifelse(grepl ("$75,000 - $95,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$35,000 - $63,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$79,000 - $111,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$50,000 - $69,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£43,701 - £61,000" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)


#bucket 5
MV_final$income_annual<- ifelse(grepl ("$96,000 - $199,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$96,000 -  $199,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$64,000 - $83,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$112,000 - $159,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$112,000 -  $159,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$70,000 -  $99,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$70,000 - $99,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£61,001 - £92,400" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)


#bucket 6
MV_final$income_annual<- ifelse(grepl ("More than $200,000" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than $83,999" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than $160,000" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than $100,000" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than £92,401" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)

#str(MV_final$income_annual)
######

#MV_final <- droplevels(subset(MV_final, income_annual != "I don't know"))


##recode gender
MV_final$Gender<- ifelse(grepl ("Transgender female" , MV_final$Gender, fixed=TRUE),"Other", MV_final$Gender)
MV_final$Gender<- ifelse(grepl ("Transgender male" , MV_final$Gender, fixed=TRUE),"Other", MV_final$Gender)
MV_final$Gender<- ifelse(grepl ("Non-binary/non-conforming" , MV_final$Gender, fixed=TRUE),"Other", MV_final$Gender)

#make edu asp numeric
MV_final$Edu_asp<- as.numeric(MV_final$Edu_asp)



```


```{r some more data wrangling}



#dummy code trait
MV_final<- pivot_longer(
  MV_final,
  cols=(c(Smart, Behave, Grades)),
  names_to = "Trait",
  values_to = "Conformity_pref",
  values_drop_na = TRUE
)

MV_final<- pivot_longer(
  MV_final,
  cols=(c(Smart_reason, Behave_reason, Grades_reason)),
  names_to = "Trait_why",
  values_to = "Why",
  values_drop_na = TRUE
)

#convert all binary IVs to factors
MV_final <- within(MV_final, {
  Trait <- factor(Trait)
  Video_Gender <- factor(Video_Gender)
  parent <- factor(parent)
  Gender <- factor(Gender)
  Why <-factor(Why)
})

MV_income_omit <- droplevels(subset(MV_final, income_annual != "I don't know"))
MV_income_omit$income_annual

write.csv(MV_final,"MV_final.csv", row.names = FALSE, fileEncoding = 'UTF-8')


###check data length
 length(which(MV_final$Country=="Australia"& MV_final$Trait=="Behave"))
 
 
 
 #Create Subdatasets by country
 
US_data<- MV_final[MV_final$Country == "US",]
US_smart<-US_data[US_data$Trait == "Smart",]
US_behave<-US_data[US_data$Trait == "Behave",]
US_grades<-US_data[US_data$Trait == "Grades",]

UK_data<- MV_final[MV_final$Country == "UK",]
UK_smart<-UK_data[UK_data$Trait == "Smart",]
UK_behave<-UK_data[UK_data$Trait == "Behave",]
UK_grades<-UK_data[UK_data$Trait == "Grades",]

CA_data<- MV_final[MV_final$Country == "Canada",]
CA_smart<-CA_data[CA_data$Trait == "Smart",]
CA_behave<-CA_data[CA_data$Trait == "Behave",]
CA_grades<-CA_data[CA_data$Trait == "Grades",]

NZ_data<- MV_final[MV_final$Country == "NZ",]
NZ_smart<-NZ_data[NZ_data$Trait == "Smart",]
NZ_behave<-NZ_data[NZ_data$Trait == "Behave",]
NZ_grades<-NZ_data[NZ_data$Trait == "Grades",]

AU_data<- MV_final[MV_final$Country == "Australia",]
AU_smart<-AU_data[AU_data$Trait == "Smart",]
AU_behave<-AU_data[AU_data$Trait == "Behave",]
AU_grades<-AU_data[AU_data$Trait == "Grades",]

```


```{r reliability}

library(psych)

##Natalia and Ajna
#IRR <- read_csv("IRR.csv")
#IRR<-drop_na(IRR)
#
#IRR<- as.data.frame(IRR)
#
#cohen.kappa(IRR)

```

```{r power}

# Load necessary libraries
#library(lme4)
#library(sjstats)
#library(psych)


#model<- glmer(Conformity_pref ~ Trait + Video_Gender + Country+ Age+ SES+ Education +(1 | PID) , data = MV_final, family=binomial(link = "logit"))


# Calculate R-squared for fixed effects
#r_squared <- performance::r2(model)


# Calculate ICC
#icc <- performance::icc(model)

# Calculate standardized coefficients
#std_coefs <-standardize(model)

# Print results
#cat("R-squared for fixed effects: ", r_squared$fixed[2], "\n")
#cat("icc: ", icc, "\n")
#cat("Standardized coefficients:\n")
#print(std_coefs)

#icc
#r_squared
#model
```

