---
title: "Multivocal - WEIRD Countries"
author: "Ajna Kertesz"
date: "6/23/2022"
output: html_document
---


```{r setup}
knitr::opts_chunk$set(fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```



```{r load data}
library(tidyverse)
library(readr)
library(dplyr)
library(likert)
library(psych)
library(knitr)
library(plyr)
library(sjPlot)
library(mudata2)
library(utils)
library(car)
library(lme4)

MV_WEIRD <- read_csv("MV_WEIRD_Complete.csv")

 #select variables
MV_final = MV_WEIRD %>% dplyr::select(Smart, Behave, Grades, Age, Gender, Country, Video_Gender, parent, Education, PID, SES, Edu_asp, income_annual, occupation) %>%  
  mutate(Age = as.numeric(Age),
        parent= ifelse(MV_WEIRD$parent=="Yes",1,0))


#recode countries to meaningful characters
MV_final$Country<- recode_factor(MV_final$Country, `1`="US", `2`="Canada", `3`="UK", `4`="Australia", `5`="NZ")

#recode education to less groups
MV_final$Education<- ifelse(grepl("Associate's defree or Certificate/Diploma", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Bachelor's degree or Honors degree", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Associate's degree or Certificate/Diploma", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Some high/secondary school",
MV_final$Education, fixed=TRUE), "Some high school or high school", MV_final$Education)

MV_final$Education<- ifelse(grepl("High/Secondary school",
MV_final$Education, fixed=TRUE), "Some high school or high school", MV_final$Education)

MV_final$Education<- ifelse(grepl("Master's degree",
MV_final$Education, fixed=TRUE), "Post-graduate Degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("PhD or other higher postgraduate degrees",
MV_final$Education, fixed=TRUE), "Post-graduate Degree", MV_final$Education)

MV_final$Education<- ifelse(grepl ("Some high school or high school" , MV_final$Education, fixed=TRUE),"1", MV_final$Education)
MV_final$Education<- ifelse(grepl ("Some college/university" , MV_final$Education, fixed=TRUE),"2", MV_final$Education)

MV_final$Education<- ifelse(grepl ( "Bachelor’s degree or Associate’s degree", MV_final$Education, fixed=TRUE),"3", MV_final$Education)
MV_final$Education<- ifelse(grepl ("Post-graduate Degree" , MV_final$Education, fixed=TRUE),"4", MV_final$Education)

#make education numeric, so we can use it in the analysis
MV_final$Education<- as.numeric(MV_final$Education)


#recode edu asp to numerical values
MV_final$Edu_asp<- ifelse(grepl ("Some high/secondary school" , MV_final$Edu_asp, fixed=TRUE),"1", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("High/Secondary school" , MV_final$Edu_asp, fixed=TRUE),"2", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Some college/university" , MV_final$Edu_asp, fixed=TRUE),"3", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Associate's degree or Certificate/Diploma" , MV_final$Edu_asp, fixed=TRUE),"4",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Bachelor's degree or Honors degree" , MV_final$Edu_asp, fixed=TRUE),"5",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Master's degree" , MV_final$Edu_asp, fixed=TRUE),"6",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("PhD or other higher postgraduate degrees" , MV_final$Edu_asp, fixed=TRUE),"6",MV_final$Edu_asp)


#recode income
#bucket 1
MV_final$income_annual<- ifelse(grepl ("Less than $22,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than $7,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than $21,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than $14,999" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("Less than - £21,000" , MV_final$income_annual, fixed=TRUE),"1", MV_final$income_annual)



#bucket 2
MV_final$income_annual<- ifelse(grepl ("$23,000 - $42,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$8,000 - $16,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$22,000 - $44,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$15,000  - $29,999" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£21,001 - £27,700" , MV_final$income_annual, fixed=TRUE),"2", MV_final$income_annual)


#bucket 3
MV_final$income_annual<- ifelse(grepl ("$43,000 - $74,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$17,000 - $34,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$45,000 - $78,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$30,000  - $49,999" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£27,701 - £43,700" , MV_final$income_annual, fixed=TRUE),"3", MV_final$income_annual)



#bucket 4
MV_final$income_annual<- ifelse(grepl ("$75,000 - $95,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$35,000 - $63,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$79,000 - $111,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$50,000 - $69,999" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£43,701 - £61,000" , MV_final$income_annual, fixed=TRUE),"4", MV_final$income_annual)


#bucket 5
MV_final$income_annual<- ifelse(grepl ("$96,000 - $199,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$64,000 - $83,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$112,000 -  $159,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("$70,000 -  $99,999" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("£61,001 - £92,400" , MV_final$income_annual, fixed=TRUE),"5", MV_final$income_annual)


#bucket 6
MV_final$income_annual<- ifelse(grepl ("More than $200,000" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than $83,999" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than $160,000" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than $100,000" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)
MV_final$income_annual<- ifelse(grepl ("More than £92,401" , MV_final$income_annual, fixed=TRUE),"6", MV_final$income_annual)

#make edu asp numeric
MV_final$Edu_asp<- as.numeric(MV_final$Edu_asp)


#dummy code trait
MV_final<- pivot_longer(
  MV_final,
  cols=(c(Smart, Behave, Grades)),
  names_to = "Trait",
  values_to = "Conformity_pref",
  values_drop_na = TRUE
)

#convert all binary IVs to factors
MV_final <- within(MV_final, {
  Trait <- factor(Trait)
  Video_Gender <- factor(Video_Gender)
  parent <- factor(parent)
})


MV_income_omit <- droplevels(subset(MV_final, income_annual != "I don't know"))
MV_income_omit

```

## Conformity Judgments

```{r  conformity}


######
#null model: just trait and video gender 

MV_final$Country<- relevel(MV_final$Country, ref="NZ")

trait_model0<- glmer(Conformity_pref ~ Trait + Video_Gender + Country + (1 | PID) , data = MV_final, family=binomial(link = "logit"))

summary(trait_model0)

#model1: all demographic factors

trait_model1<- glmer(Conformity_pref ~ Trait + Video_Gender + Country+ SES+  Age+ Education+ Gender+ Edu_asp+(1 | PID) , data = MV_final, family=binomial(link = "logit"))

summary(trait_model1) 

#model2: final model with only education, age and edu asp as controls (based on literature)

trait_model2<- glmer(Conformity_pref ~ Trait + Video_Gender + Country+ Age+ Education+ Edu_asp+ (1 | PID) , data = MV_final, family=binomial(link = "logit"))

summary(trait_model2)
ANOV<-anova(trait_model2, test = "f")

summary(ANOV)

aov(trait_model2)

tab_model(trait_model2)
pf(5.091, 2, 9, lower.tail=FALSE)


anova(trait_model0,trait_model1, trait_model2) #interestingly the full model (all controls) has a better AIC, so maybe we can leave in all those demo factors?

tab_model(trait_model0, trait_model1, trait_model2)

#income added -> not significant
income_model<- glmer(Conformity_pref ~ Trait + Video_Gender + Country+ Edu_asp + income_annual+ (1 | PID) , data = MV_income_omit, family=binomial(link = "logit"))

summary(income_model)

#income only
income_only_model<- glmer(Conformity_pref ~ Trait + income_annual+ (1 | PID) , data = MV_income_omit, family=binomial(link = "logit"))

summary(income_only_model)

#occupation only model -> not significant
MV_final$occupation<- ifelse(grepl(",", MV_final$occupation, fixed=TRUE), "More than one type of job", MV_final$occupation)

occup_model<- glmer(Conformity_pref ~ Trait + occupation + (1 | PID) , data = MV_final, family=binomial(link = "logit"))

summary(occup_model)


#pairwise comparison
pairwise.t.test(MV_final$Conformity_pref, MV_final$Trait, p.adjust.method = "bonferroni")

# post hoc for multiple linear regression
library(multcomp) # for adjusted
library(emmeans) # for as.glht, pairs, emmeans
library(lsmeans)
trait_model<- lsmeans::ref.grid(trait_model2)
summary(emmeans::as.glht(pairs(emmeans::emmeans(trait_model, ~ Conformity_pref*Trait))), test=adjusted(type="holm"))
# or, using the Tukey HSD correction instead of Holm's
summary(emmeans::emmeans(trait_model, pairwise ~ Gender*Trait, adjust="tukey", mode="linear.predictor", type="Score"))

trait_model

#visual
#create prop table
#Conf_prop<-prop.table(table(MV_final_c$Conformity_pref, MV_final_c$Trait), margin=2)

conf_prop<-prop.table(with(MV_final, table(Conformity_pref, Trait, Video_Gender, Country)), margin=2)
                      
conf_prop<- as.data.frame(conf_prop)

conf_prop<-conf_prop[!(conf_prop$Conformity_pref == 0),]


#calaculate errors 

df1 <- conf_prop %>% mutate(sd = sd(Freq))

df1$Country=as.factor(df1$Country)

head(df1)

### create first figure
#plot relative proportions (almost works but the y-axies is weird)
ggplot(df1, 
       aes(Video_Gender, y = Freq, x = Country, color = Video_Gender)) + 
  geom_point(stat = "summary", fun.y = "mean", shape= 16, size =3, position = position_dodge(width = 1)) +
  geom_errorbar(aes(ymin = Freq - sd, ymax = Freq + sd),linetype = "dotted", position = position_dodge(width = 1))+
  facet_wrap(vars(Trait)) + 
  ylab ("Proportion of Conformity Endorsement") +
  scale_fill_discrete(name = "Gender", labels = c("Male", "Female"))


```

## Teaching attributes by country

```{r teach}

library(dplyr)

#select teaching items
MV_teaching= MV_WEIRD %>% dplyr::select (Teach_expect_1, Teach_expect_2, Teach_expect_3, Teach_expect_4, Teach_expect_5, Teach_expect_6, Country, PID)


#dummy code teaching
MV_teaching<- pivot_longer(
  MV_teaching,
  cols=(c(Teach_expect_1, Teach_expect_2, Teach_expect_3, Teach_expect_4, Teach_expect_5, Teach_expect_6)),
  names_to = "Teaching style",
  values_to = "Ranking",
  values_drop_na = TRUE
)

#recode countries to meaningful characters
MV_teaching$Country<- recode_factor(MV_teaching$Country, `1`="US", `2`="Canada", `3`="UK", `4`="Australia", `5`="NZ")

#recode teaching style
MV_teaching$`Teaching style`<- ifelse(grepl("Teach_expect_1", MV_teaching$`Teaching style`, fixed=TRUE), "Rote", MV_teaching$`Teaching style`)
MV_teaching$`Teaching style`<- ifelse(grepl("Teach_expect_2", MV_teaching$`Teaching style`, fixed=TRUE), "Rote", MV_teaching$`Teaching style`)
MV_teaching$`Teaching style`<- ifelse(grepl("Teach_expect_5", MV_teaching$`Teaching style`, fixed=TRUE), "Rote", MV_teaching$`Teaching style`)

MV_teaching$`Teaching style`<- ifelse(grepl("Teach_expect_3", MV_teaching$`Teaching style`, fixed=TRUE), "Free", MV_teaching$`Teaching style`)
MV_teaching$`Teaching style`<- ifelse(grepl("Teach_expect_4", MV_teaching$`Teaching style`, fixed=TRUE), "Free", MV_teaching$`Teaching style`)

MV_teaching$`Teaching style`<- ifelse(grepl("Teach_expect_6", MV_teaching$`Teaching style`, fixed=TRUE), "Balanced", MV_teaching$`Teaching style`)

#calaculate errors with function

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}


#add errors to dataframe (geom_errorbar...)

df <- data_summary(MV_teaching, varname = "Ranking",
                            groupnames=c("Country","`Teaching style`" ))

df$Country=as.factor(df$Country)
df$`Teaching style`=as.factor(df$`Teaching style`)

##create second figure

ggplot(df,
       aes(`Teaching style`, y= Ranking, x= Country, fill=`Teaching style`, color=`Teaching style`)) +
  geom_point(stat = "summary", fun.y = "mean", shape = 16, size =3, position=position_dodge(width=0.5)) +
  geom_errorbar(aes(ymin = Ranking - sd, ymax = Ranking + sd, width=0.5), linetype = "dotted", position=position_dodge(width=0.5))+
  scale_y_continuous() +
  ylab("Preference") +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "right")
  
  

```
## Latent Class Analysis

```{r lca}
#install.packages("devtools")
#devtools::install_github("dr-JT/datawrangling")
library(datawrangling)
library(poLCA)
library(reshape2)

#select variables and reformat data so we have 3 columns with numerical values

MV_teaching<- MV_WEIRD %>% dplyr::select (Teach_expect_1, Teach_expect_2, Teach_expect_3, Teach_expect_4, Teach_expect_5, Teach_expect_6, Country, PID, Smart, Behave, Grades, Video_Gender)

#dummy code trait
MV_teachingLCA<- pivot_longer(
  MV_teaching,
  cols=(c(Smart, Behave, Grades)),
  names_to = "Trait",
  values_to = "Conformity_pref",
  values_drop_na = TRUE
)

#convert all binary IVs to factors
MV_teachingLCA <- within(MV_teachingLCA, {
  Trait <- factor(Trait)
  Video_Gender <- factor(Video_Gender)
})

MV_teachingLCA$Country<- recode_factor(MV_teachingLCA$Country, `1`="US", `2`="Canada", `3`="UK", `4`="Australia", `5`="NZ")

MV_teachingLCA<-drop_na(MV_teachingLCA)

MV_teachingLCA<- MV_teachingLCA %>%
  datawrangling::composite(variables = c("Teach_expect_1", "Teach_expect_2", "Teach_expect_5"), name = "Rote", standardize = FALSE)

MV_teachingLCA<- MV_teachingLCA %>%
  datawrangling::composite(variables = c("Teach_expect_3", "Teach_expect_4"), name = "Free", standardize = FALSE)

MV_teachingLCA<- MV_teachingLCA %>%
  datawrangling::composite(variables = c("Teach_expect_6"), name = "Balanced", standardize = FALSE)

library(mclust)
library(tidyLPA)

MV_teaching<- as_tibble(MV_teaching)

#rename teaching items to meaningful labels

dplyr::rename(MV_teaching, outcome = Teach_expect_1) -> MV_teaching
dplyr::rename(MV_teaching, instructions = Teach_expect_2) -> MV_teaching
dplyr::rename(MV_teaching, exploration = Teach_expect_3) -> MV_teaching
dplyr::rename(MV_teaching, teamwork = Teach_expect_4) -> MV_teaching
dplyr::rename(MV_teaching, modelling = Teach_expect_5) -> MV_teaching
dplyr::rename(MV_teaching, neutral = Teach_expect_6) -> MV_teaching

#try LCA with 1 class only

teach1 <- MV_teaching%>% 
  dplyr::select(Teach_expect_1, Teach_expect_2, Teach_expect_3, Teach_expect_4, Teach_expect_5, Teach_expect_6) %>% 
  single_imputation() %>% 
  estimate_profiles(1)%>%
  print()

# 2 classes

teach2 <- MV_teaching%>% 
  dplyr::select(Teach_expect_1, Teach_expect_2, Teach_expect_3, Teach_expect_4, Teach_expect_5, Teach_expect_6) %>% 
  single_imputation() %>% 
  estimate_profiles(2)%>%
  print()

#three classes -> final model

teach3 <- MV_teaching%>% 
  dplyr::select(outcome, instructions, exploration, teamwork, modelling, neutral) %>% 
  single_imputation() %>% 
  estimate_profiles(3)
  
#compare 1-3 models
teach13 <- MV_teaching%>% 
  dplyr::select(Teach_expect_1, Teach_expect_2, Teach_expect_3, Teach_expect_4, Teach_expect_5, Teach_expect_6) %>% 
  single_imputation() %>% 
  estimate_profiles(1:3)

#visualize the 3 classess model  

plot_profiles(teach3, add_line=TRUE)
plot_density(teach3)
plot_bivariate(teach3)


#save LCA as a tibble
MV_teachLCA<-get_data(teach3)
get_fit(teach13)
get_estimates(teach13)

#merge class status to the original dataset

total <- cbind(MV_WEIRD,MV_teachLCA)

MV_WEIRD_total<- pivot_longer(
  total,
  cols=(c(Smart, Behave, Grades)),
  names_to = "Trait",
  values_to = "Conformity_pref",
  values_drop_na = TRUE
)

#convert all binary IVs to factors
MV_WEIRD_total <- within(MV_WEIRD_total, {
  Trait <- factor(Trait)
  Video_Gender <- factor(Video_Gender)
  parent <- factor(parent)
  Class<- factor(Class)
})

#run multi level multiple regression with class identity -> significant!
class_model<- glmer(Conformity_pref ~ Trait + Video_Gender + Class +(1 | PID) , data = MV_WEIRD_total, family=binomial(link = "logit"))

#summarize and view model
summary(class_model)
tab_model(class_model)
```





```{r learning strat}

library(mix)


MV_learning= MV_WEIRD %>% dplyr::select (Observation, Exploration, Copy, Instructions, Collabs, Country, PID, Education, )

#recode countries to meaningful characters
MV_learning$Country<- recode_factor(MV_learning$Country, `1`="US", `2`="Canada", `3`="UK", `4`="Australia", `5`="NZ")

MV_final = MV_WEIRD %>% dplyr::select(Smart, Behave, Grades, Age, Gender, Country, Video_Gender, parent, Education, PID, SES, Edu_asp, income_annual, occupation) %>%  
  mutate(Age = as.numeric(Age),
        parent= ifelse(MV_WEIRD$parent=="Yes",1,0))


#recode countries to meaningful characters
MV_final$Country<- recode_factor(MV_final$Country, `1`="US", `2`="Canada", `3`="UK", `4`="Australia", `5`="NZ")

#recode education to less groups
MV_final$Education<- ifelse(grepl("Associate's defree or Certificate/Diploma", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Bachelor's degree or Honors degree", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Associate's degree or Certificate/Diploma", MV_final$Education, fixed=TRUE), "Bachelor’s degree or Associate’s degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("Some high/secondary school",
MV_final$Education, fixed=TRUE), "Some high school or high school", MV_final$Education)

MV_final$Education<- ifelse(grepl("High/Secondary school",
MV_final$Education, fixed=TRUE), "Some high school or high school", MV_final$Education)

MV_final$Education<- ifelse(grepl("Master's degree",
MV_final$Education, fixed=TRUE), "Post-graduate Degree", MV_final$Education)

MV_final$Education<- ifelse(grepl("PhD or other higher postgraduate degrees",
MV_final$Education, fixed=TRUE), "Post-graduate Degree", MV_final$Education)

MV_final$Education<- ifelse(grepl ("Some high school or high school" , MV_final$Education, fixed=TRUE),"1", MV_final$Education)
MV_final$Education<- ifelse(grepl ("Some college/university" , MV_final$Education, fixed=TRUE),"2", MV_final$Education)

MV_final$Education<- ifelse(grepl ( "Bachelor’s degree or Associate’s degree", MV_final$Education, fixed=TRUE),"3", MV_final$Education)
MV_final$Education<- ifelse(grepl ("Post-graduate Degree" , MV_final$Education, fixed=TRUE),"4", MV_final$Education)

#make education numeric, so we can use it in the analysis
MV_final$Education<- as.numeric(MV_final$Education)


#recode edu asp to numerical values
MV_final$Edu_asp<- ifelse(grepl ("Some high/secondary school" , MV_final$Edu_asp, fixed=TRUE),"1", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("High/Secondary school" , MV_final$Edu_asp, fixed=TRUE),"2", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Some college/university" , MV_final$Edu_asp, fixed=TRUE),"3", MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Associate's degree or Certificate/Diploma" , MV_final$Edu_asp, fixed=TRUE),"4",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Bachelor's degree or Honors degree" , MV_final$Edu_asp, fixed=TRUE),"5",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("Master's degree" , MV_final$Edu_asp, fixed=TRUE),"6",MV_final$Edu_asp)
MV_final$Edu_asp<- ifelse(grepl ("PhD or other higher postgraduate degrees" , MV_final$Edu_asp, fixed=TRUE),"6",MV_final$Edu_asp)

#calaculate errors with function

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}


#reorder learning srategies
MV_learning<- pivot_longer(
  MV_learning,
  cols=(c(Observation, Exploration, Copy, Instructions, Collabs)),
  names_to = "Learning",
  values_to = "Ranking",
  values_drop_na = TRUE
)

#add errors to dataframe (geom_errorbar...)

df <- data_summary(MV_learning, varname = "Ranking",
                            groupnames=c("Country","Learning" ))

df$Country=as.factor(df$Country)
df$Learning=as.factor(df$Learning)



ggplot(df,
       aes(Learning, y= Ranking, x= Country, fill=Learning, color=Learning)) +
  geom_point(stat = "summary", fun.y = "mean", shape = 16, size =3, position=position_dodge(width=0.5)) +
  geom_errorbar(aes(ymin = Ranking - sd, ymax = Ranking + sd, width=0.5), linetype = "dotted", position=position_dodge(width=0.5))+
  scale_y_continuous() +
  ylab("Preference") +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "right")
  




learn3 <- MV_WEIRD%>% 
  dplyr::select(Observation, Exploration, Copy, Instructions, Collabs) %>% 
  single_imputation() %>% 
  estimate_profiles(3)

plot_profiles(learn3, add_line=TRUE)


```





