---
title: "MV proportion tests"
author: "Ajna Kertesz"
date: '2022-08-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prop test}
library(tidyverse)
library(readr)
library(dplyr)
library(psych)
library(knitr)
library(plyr)


MV_final <- read.csv("MV_final.csv")

############make tables
table(MV_final$Video_Gender, MV_final$Trait, MV_final$Conformity_pref, MV_final$Why, MV_final$Country)

table(MV_final$Video_Gender, MV_final$Trait, MV_final$Conformity_pref)

table(MV_final$Trait, MV_final$Conformity_pref)

###difference between Traits

##Smart (low vs high)
prop.test(1209, 3681, p = NULL,
          alternative = c("two.sided"),
          conf.level = 0.95, correct = TRUE)
##Behave(low vs high)
prop.test(624, 3666, p = NULL,
          alternative = c("two.sided"),
          conf.level = 0.95, correct = TRUE)
##Grades(low vs high)
prop.test(963, 3681, p = NULL,
          alternative = c("two.sided"),
          conf.level = 0.95, correct = TRUE)

##Smart vs Grades in low conformity
prop.test(x=c(1209, 963), n=c(4005,4005), p = NULL,
          alternative = "two.sided",
          conf.level = 0.95, correct = TRUE)

##Behave vs Grades in low conformity
prop.test(x=c(624, 963), n=c(4005,4005), p = NULL,
          alternative = "two.sided",
          conf.level = 0.95, correct = TRUE)

##Smart vs Grades in high conformity

prop.test(x=c(2472, 2718), n=c(8232,8232), p = NULL,
          alternative = "two.sided",
          conf.level = 0.95, correct = TRUE)

##Behave vs Grades in high conformity
prop.test(x=c(2472, 2718), n=c(8232,8232), p = NULL,
          alternative = "two.sided",
          conf.level = 0.95, correct = TRUE)

###visual tables

library(janitor)
library(table1)

table1(~ Trait  | Video_Gender*Conformity_pref, data=MV_final)
table1(~ Country  | Video_Gender*Conformity_pref, data=MV_final)
table1(~ Country  | Trait*Conformity_pref, data=MV_final)


```